site_name: My Docs

nav:
  - Home: index.md
  - Лабораторная 1:
    - task1: lab1/task1.md
    - task2: lab1/task2.md
    - task3: lab1/task3.md
    - task4: lab1/task4.md
    - task5: lab1/task5.md
  - Лабораторная 2: lab2.md
  - Практическая 3.1: practical3_1.md
  - Лабораторная 3: lab3.md
  - Лабораторная 4: lab4.md

site_url: https://blkrv.github.io/ITMO_ICT_WebDevelopment_2024-2025/
theme:
  name: material
